# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_list.ui'
#
# Created: Wed Dec  9 16:42:38 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(485, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeWidget = QtGui.QTreeWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeWidget.setAllColumnsShowFocus(True)
        self.treeWidget.setExpandsOnDoubleClick(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.verticalLayout.addWidget(self.treeWidget)
        self.refreshButton = QtGui.QPushButton(self.frame)
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.verticalLayout.addWidget(self.refreshButton)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.verticalFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalFrame.setObjectName(_fromUtf8("verticalFrame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(12)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.taskTimerWidget = QtGui.QFrame(self.verticalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskTimerWidget.sizePolicy().hasHeightForWidth())
        self.taskTimerWidget.setSizePolicy(sizePolicy)
        self.taskTimerWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.taskTimerWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.taskTimerWidget.setObjectName(_fromUtf8("taskTimerWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.taskTimerWidget)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.taskLabel = QtGui.QLabel(self.taskTimerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskLabel.sizePolicy().hasHeightForWidth())
        self.taskLabel.setSizePolicy(sizePolicy)
        self.taskLabel.setObjectName(_fromUtf8("taskLabel"))
        self.verticalLayout_3.addWidget(self.taskLabel)
        self.comboBox = QtGui.QComboBox(self.taskTimerWidget)
        self.comboBox.setEditable(False)
        self.comboBox.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout_3.addWidget(self.comboBox)
        self.timeLabel = QtGui.QLabel(self.taskTimerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.timeLabel.setFont(font)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.verticalLayout_3.addWidget(self.timeLabel)
        self.progressBar = QtGui.QProgressBar(self.taskTimerWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_4.addWidget(self.taskTimerWidget)
        self.frame_3 = QtGui.QFrame(self.verticalFrame)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.workButton = QtGui.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8(".Helvetica Neue DeskInterface"))
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.workButton.setFont(font)
        self.workButton.setStyleSheet(_fromUtf8("font: 24pt;\n"
"color: rgb(0, 128, 64);padding: 18px;"))
        self.workButton.setCheckable(True)
        self.workButton.setChecked(False)
        self.workButton.setAutoExclusive(True)
        self.workButton.setObjectName(_fromUtf8("workButton"))
        self.horizontalLayout.addWidget(self.workButton)
        self.breakButton = QtGui.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8(".Helvetica Neue DeskInterface"))
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.breakButton.setFont(font)
        self.breakButton.setStyleSheet(_fromUtf8("color: rgb(128, 0, 0); padding: 18px;\n"
""))
        self.breakButton.setCheckable(True)
        self.breakButton.setAutoExclusive(True)
        self.breakButton.setAutoDefault(False)
        self.breakButton.setDefault(False)
        self.breakButton.setFlat(False)
        self.breakButton.setObjectName(_fromUtf8("breakButton"))
        self.horizontalLayout.addWidget(self.breakButton)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.verticalFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setSizeGripEnabled(True)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 485, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuAction = QtGui.QMenu(self.menuBar)
        self.menuAction.setObjectName(_fromUtf8("menuAction"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionWork = QtGui.QAction(MainWindow)
        self.actionWork.setObjectName(_fromUtf8("actionWork"))
        self.actionBreak = QtGui.QAction(MainWindow)
        self.actionBreak.setObjectName(_fromUtf8("actionBreak"))
        self.menuAction.addAction(self.actionWork)
        self.menuAction.addAction(self.actionBreak)
        self.menuBar.addAction(self.menuAction.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.refreshButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.refreshTaskPicker)
        QtCore.QObject.connect(self.treeWidget, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QTreeWidgetItem*,int)")), MainWindow.go)
        QtCore.QObject.connect(self.workButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.go)
        QtCore.QObject.connect(self.breakButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.pause)
        QtCore.QObject.connect(self.actionWork, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.go)
        QtCore.QObject.connect(self.actionBreak, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.pause)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Task List", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Task", None))
        self.refreshButton.setText(_translate("MainWindow", "Refresh", None))
        self.taskLabel.setText(_translate("MainWindow", "Task", None))
        self.timeLabel.setText(_translate("MainWindow", "Time", None))
        self.workButton.setText(_translate("MainWindow", "Work", None))
        self.breakButton.setText(_translate("MainWindow", "Break", None))
        self.menuAction.setTitle(_translate("MainWindow", "Action", None))
        self.actionWork.setText(_translate("MainWindow", "Work", None))
        self.actionBreak.setText(_translate("MainWindow", "Break", None))

